version: '3.8'

services:
  posformer-api:
    build: .
    container_name: posformer-api
    ports:
      - "5000:8000"
    volumes:
      - ./:/app/
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: unless-stopped
    environment:
      - CUDA_VISIBLE_DEVICES=0